# Generated by Django 5.1 on 2024-08-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTomas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='products',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='precio',
            new_name='price',
        ),
    ]
